### ISSUE TITLE
Map to custom struct while making join.

### ISSUE THREAD

**Issue by uwejan** [jgirardet/sqlo#3]
```
create table firms_users(
  firm_id integer references firms(id),
  user_id integer references users(id),
  primary key (firm_id, user_id)
);
```
How would I join on this table note the intended result would be some of users attributes + some of firm attributes not the whole model.

```
pub struct UserWithFirm {
    pub(crate) user: SlimUser,
    pub(crate) firm: SlimFirm,
}
```

Thank you.

**Comment by jgirardet** [comment]
Hi,
some things about it:
- we do not yet support composite primary key
- mapping to custom struct is not  `sqlo`'s thing it's `sqlx`'s one. https://docs.rs/sqlx/latest/sqlx/types/trait.Type.html. 
- I'm not sure you can   reference ids in your sql code  an map to a struct in your rust code with sqlx.

Please show we a working example with sqlx of what you mean and i'll see. 
Sqlo just converts to sqlx::query_as! so what sqlx can do, I think we might also do it.

**Comment by uwejan** [comment]
Hey, 
Thank you for looking into this. I actually still have not implemented the sqlx part yet, I am still drawing, and reading docs.
Since there is not an immediate action to be taken please feel free to close it.

**Comment by jgirardet** [comment]
Ok I close.
I add to my todo list composite primary keys and "reverse relationship"
